ALTER TABLE spareparts_prices
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE venues
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE maintenance_schedule
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE servicelogs
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE servicelogs_spareparts
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE stores
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;

ALTER TABLE spareparts
ALTER COLUMN created_at TYPE TIMESTAMPTZ,
ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
ALTER COLUMN deleted_at TYPE TIMESTAMPTZ;